### ISSUE TITLE
New schema for indicators

### ISSUE THREAD

**Issue by brandomr** [uncharted-causemos/docs#7]
I propose we create a new schema for indicators. Let's define "indicator" to be any *non-model generated structured dataset*. These datasets may be from the UAZ set of indicators or may be part of the "BYOData" pipeline.

I feel that they are sufficiently different from datacubes and models to warrant their own schema. For example, each datacube must have associated `parameters`, whereas an indicator will _never have parameters_. Similarly, much of the required metadata for a model is irrelevant for an indicator (e.g. `parameters` and `outputs`).

I suggest the metadata schema for an indicator look like a hybrid of the model and datacube schema. Perhaps something like:

```
{
  "$schema": "./indicator.schema.json",
  "id": "123e4567-e89b-12d3-a456-426614174000",
  "name": "ACLED Africa",
  "description": "The Armed Conflict Location & Event Data Project (ACLED) is a disaggregated data collection, analysis, and crisis mapping project. ACLED is the highest quality",
  "created": "2021-01-01T00:00:00Z",
  "created_by": {
    "name": "Bob Fakename",
    "organization": "MITRE",
    "email": "bob@mitre.org"
  },
  "category": [
    "Conflict"
  ],
  "url": [
    "https://jataware-world-modelers.s3.amazonaws.com/ACLED/data.csv"
  ],
  "geography": {
    "country": [
      "Ethiopia",
      "South Sudan",
      "Kenya"
    ]
  },
  "periods": [
    {
      "gte": "2019-01-01T00:00:00Z",
      "lte": "2020-01-01T00:00:00Z",
      "resolution": "daily"
    }
  ]
}
```

> Note: we assume that the actual data schema for indicators/structured data available at `url` in the metadata above will be in the CauseMos compliant format.

**Comment by mkozlowski-uncharted** [comment]
Thanks!

I agree with having a separate schema for the indicators.
I think that this schema should be a subset of the model schema since that would make it easiest to store and work with. I believe the only thing that needs to change for that to be the case is to add the `periods` section into the model schema. Which, if I am recalling correctly, we were already discussing before.

In terms of this indicator schema, there is some additional information we need to capture with respect to the output. I think that we should add the `outputs` field. Even if we don't utilize all the internal fields, we need things like `name`, `display_name`, `unit`, `unit_description`, and `concepts`. We should keep `outputs` as an array to maintain compatibility with the model schema but we might be able to restrict it to only one element.

**Comment by brandomr** [comment]
This sounds good to me. When the user annotates the indicator we will get `outputs` anyway. The indicators coming from the Datamart may be an exception to this.

We'll start working using a strawman of this as you lock down the indicator schema.
